name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: CMake - Configure ${{ matrix.targets }}
        run: cmake -B build -DFACIL_TESTS_BUILD=ON -DFACIL_EXAMPLES_BUILD=ON

      - name: CMake - Build ${{ matrix.targets }}
        run: cmake --build build --parallel
