name: Windows MingW CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        cc: 1
    - name: Test No-Op (debug)
      run: cc -O0 -fstack-protector-all tests\noop.c -I. -DFIO_LEAK_COUNTER=1 -DDEBUG -o ./noop.exe && ./noop.exe
    - name: Test STL (debug) - no allocators
      run: cc -O0 -fstack-protector-all tests\stl.c -I. -DFIO_MEMORY_DISABLE=1 -DFIO_LEAK_COUNTER=1 -DDEBUG -o ./stl.exe && ./stl.exe
    - name: Test fio_mallc speed
      run: cc -O2 -march=native tests\malloc.c -I. -o ./malloc.exe && ./malloc.exe
    - name: Test STL
      run: cc -O2 -march=native tests\stl.c -DFIO_LEAK_COUNTER=1 -I. -o ./stl.exe && ./stl.exe
